### ISSUE TITLE
How to use FAISS when you don't know the number of clusters ahead?

### ISSUE THREAD

**Issue by smith-co** [daveshap/FAISS_demo#1]
I was looking into your demo code for FAISS.

Looks like you have to state how many clusters are there ahead of the time and then vectors are clustered into that given number of clusters.
```
nlist = 5  # number of clusters
```

However, what would happen if I don't know the number of clusters ahead of the time. Given a set of vectors can FAISS cluster them?

**Comment by daveshap** [comment]
I tried to find documentation about best practices. Couldn't find anything. I think you just need to play around with it and gain an intuition for it.
